// This file is auto-generated by @hey-api/openapi-ts

/**
 * This command will try to create data.
 *
 */
export type CreateDataCommand = {
    data: CreateData;
};

export type CreateData = {
    uuid: string;
    firstName: string;
    lastName: string;
    channel: 'EMAIL' | 'WEB';
};

/**
 * This command will try to retrieve data.
 *
 */
export type RetrieveDataCommand = {
    data: RetrieveData;
};

export type RetrieveData = {
    uuid: ;
    firstName: string;
    lastName: string;
    channel: ;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};