// This file is auto-generated by @hey-api/openapi-ts

export type DataUuid = string;

export type Channel = 'EMAIL' | 'WEB';

export type CreateDataRequest = {
    firstName: string;
    lastName: string;
};

export type Data = {
    firstName: string;
    uuid: DataUuid;
    lastName: string;
};

export type CreateDataData = {
    body: CreateDataRequest;
    path?: never;
    query?: never;
    url: '/data';
};

export type CreateDataResponses = {
    /**
     * Returns the created customer
     */
    201: Data;
};

export type CreateDataResponse = CreateDataResponses[keyof CreateDataResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};